- .github/workflows/release.yml
It will be simpler than using an AWS ECR.
> Publish docker images to ghcr instead

- CONTRIBUTING.md
- website/src/pages/community.tsx
Some small housekeeping for the repo:
- Point to original plugin example in `benthosdev` in lieu of a forked version in `warpstreamlabs` (Related to #21)
- Change copy of social card to correctly reference `#bento` channel in WarpStream's Community Slack server.
> Chore: Fix reference to example project and update Slack card

- CHANGELOG.old.md
- Makefile
- cmd/bento/main.go
- internal/cli/blobl/cli.go
- internal/cli/common/opts.go
- internal/cli/common/reader.go
- internal/cli/common/service.go
- internal/cli/create.go
- internal/cli/lint.go
- internal/cli/list.go
- internal/cli/run.go
- internal/cli/template/cli.go
- internal/cli/template/lint.go
- internal/cli/test/cli.go
- internal/docs/json_schema.go
- public/service/service.go
Pulling in upstream changes. 
Changes:
- Add richer CLI customisation options
- ~Move `strip_html` to `internal/impl` and update docs (which generated weirdly and with an `unknown` param)~
- Include upstream `CHANGELOG` information into `CHANGELOG.old.md`
> Sync upstream changes into bento

- CHANGELOG.old.md
- internal/impl/aws/processor_dynamodb_partiql.go
- internal/impl/azure/cosmosdb/executor.go
- internal/impl/cassandra/output.go
- internal/impl/couchbase/processor.go
- internal/impl/gcp/processor_bigquery_select.go
- internal/impl/io/bloblang_examples_test.go
- internal/impl/mongodb/common.go
- internal/impl/pure/bloblang_examples_test.go
- internal/impl/pure/buffer_system_window.go
- internal/impl/pure/processor_cached.go
- internal/impl/redis/processor.go
- internal/impl/redis/script_processor.go
- internal/impl/sql/output_sql_insert.go
- internal/impl/sql/output_sql_raw.go
- internal/impl/sql/processor_sql_insert.go
- internal/impl/sql/processor_sql_raw.go
- internal/impl/sql/processor_sql_select.go
- public/bloblang/view.go
- public/service/message.go
- public/service/message_batch_blobl.go
- public/service/message_batch_blobl_test.go
@gregfurman 
Please can you take a look? 
I had an issue with some missing func `TemplateData()` in ./public/bloblang/view.go - that was added on [this commit](https://github.com/redpanda-data/benthos/commit/2f82397309490a54b8a509cbd90182b528809d21) a couple of weeks ago, I have edited the commit manually to include here. Not sure if this is best way?
> upstream changes

- CONTRIBUTING.md
- internal/api/config.go
- internal/api/docs.go
- website/docs/components/http/about.md
- website/src/pages/index.tsx
- Remove references to original project in docs.
- Comment out `asfd` and `brew` installation methods until further notice.
> Docs: Remove references to original

- internal/serverless/handler_test.go
- website/docs/guides/serverless/lambda.md
Some small fixes/improvements:
- Added some serverless handler tests
- Included short guide on local testing AWS `bento-lamba` using LocalStack 
- Added note on batches failing when exceptions are not caught (from https://github.com/warpstreamlabs/bento/issues/59#issuecomment-2195654914)
> Serverless housekeeping: Local testing guide, small docs fixes, and some handler tests for errors

- website/cookbooks/kafka_topic_mirroring.md
We have recieved a couple of questions relating to topic mirroring. Hopefully this guide can better help users get up-and-running with this faster.
- Create cookbook showing how to mirror Kafka topics while preserving original partition mapping
- Added in some processing steps to better illustrate dynamic output routing with string interpolation and metadata
> docs: Add cookbook for Kafka topic mirroring

- CHANGELOG.md
Updating CHANGELOG with `v1.0.2`  and incoming `v1.1.0` information.
> Update CHANGELOG for v1.0.2 and v1.1.0

- internal/impl/sql/cache_sql.go
- internal/impl/sql/conn_fields.go
- internal/impl/sql/input_sql_raw.go
- internal/impl/sql/input_sql_select.go
- internal/impl/sql/output_sql_insert.go
- internal/impl/sql/output_sql_raw.go
- internal/impl/sql/processor_sql_insert.go
- internal/impl/sql/processor_sql_raw.go
- internal/impl/sql/processor_sql_select.go
- website/docs/components/caches/sql.md
- website/docs/components/inputs/sql_raw.md
- website/docs/components/inputs/sql_select.md
- website/docs/components/outputs/sql_insert.md
- website/docs/components/outputs/sql_raw.md
- website/docs/components/processors/sql_insert.md
- website/docs/components/processors/sql_raw.md
- website/docs/components/processors/sql_select.md
- Add a flag that, when true, pings a SQL database. If the ping fails the component is set to an error state.
- From #70 
- Extended `sqlOpenWithReworks` to include a `shouldPing` boolean which will run a `db.PingContext` if true. 
- Small refactor of `sqlOpenWithReworks`, placing the `rework` functionality into a seperate `reworkDSN` function.
- Added new flag `init_verify_conn` to the SQL component's config and included this in the `connSettings` struct.
- Updated docs.
> sql: Add optional verification ping on database client initialisation

- internal/impl/mongodb/input.go
- internal/impl/mongodb/output.go
- internal/impl/mongodb/processor.go
- website/docs/components/inputs/mongodb.md
- website/docs/components/outputs/mongodb.md
- website/docs/components/processors/mongodb.md
Update documentation for MongoDB docs with the following:
- Reflect string interpolation functionality for `collection` field of the `output` and `processor`.
- Mention metadata being added to each message on `input`
- From #99
> mongodb: Update docs to reflect input metadata and interpolation for collection field

- internal/impl/pure/processor_workflow_test.go
- public/service/stream_builder_test.go
- public/service/tracing.go
- public/service/tracing_test.go
In case of huge transaction amount tracing summary could consume to much memory. In order to avoid this and returning same transactions every time, it's better to have a possibility to flush events on consumption.
> Enable event flushing during consumption

- internal/impl/couchbase/integration_test.go
- internal/impl/kafka/input_kafka_franz.go
- internal/impl/kafka/integration_test.go
- internal/impl/kafka/output_kafka_franz.go
- internal/impl/questdb/output.go
- internal/impl/questdb/output_test.go
- website/docs/components/inputs/kafka_franz.md
- website/docs/components/outputs/kafka_franz.md
Adds the following fields to `input.kafka_franz`:
- A list of `group_balancers` (default `cooperative_sticky`)
- `metadata_max_age` (default 5m)
- `fetch_max_bytes` (default 50MiB)
- `fetch_max_partition_bytes` (default 1MiB)
- `fetch_max_wait` (default 5s)
- `preferring_lag` (optional, no default)
Adds the following fields to `output.kafka_franz`:
- `partitioner` has a `uniform_bytes` enum
- `uniform_bytes_options` (default `{ "bytes" : "1MiB",  "adaptive" : false, "keys" : false }`)
- Note: we do not yet allow specifying a `PartitionerHasher`. This approach should probably be reworked using bloblang with some lint rule.
- `max_buffered_records` (default 10K)
- `metadata_max_age` (default 5m)
A new integration test `TestIntegrationKafkaWarpstreamDefaults` has also been added with the …
>  kafka-franz: Add more configurable fields for kafka-franz performance tuning

- internal/impl/gcp/output_bigquery_storage.go
Without this we just see a very generic "InvalidRequest"
> Log sample row errors in BQ Storage Write API response

- config/test/deduplicate_lifo.yaml
- internal/impl/pure/processor_dedupe.go
- internal/impl/pure/processor_dedupe_test.go
- website/docs/components/processors/dedupe.md
- Adds the ability to de-duplicate values in FIFO or LIFO order (FIFO by default.). 
- Adds a `strategy` key where this value can be set.
> add: LIFO option to dedupe processor

- internal/impl/io/output_http_server.go
- website/docs/components/outputs/http_server.md
At the moment http_server websocket implementation just writes to webscocket, and do not have a way to detect client disconnect proactively. More over, if client disconnects, and it fails write to it, it does not stop the handler, and continues to be inside the endless for loop, untill stream is stopped `for !h.shutSig.IsSoftStopSignalled() {`.
It cause issues when you have multiple clients connected/disconnected, because essentially it fanout using round robin to them, but if you have closed "zombie" connections, they will also consume events.
It fixes the issue by using websocket native mechanisms like "ping/pong" methods. Also it adds ephemeral "Read", just to immidiately detect the client shutdown.
> Fix "zombie" http output websocket connections 

- internal/impl/io/input_subprocess.go
- website/docs/components/inputs/subprocess.md
I noticed a small typo in the `subprocess` input documentation. The configuration field is `restart_on_exit`, but documentation refers to `restart_on_close`.
I've just fixed the wording on the source component and then executed `make docs` to generate the updated documentation.
It's a super minor change, but I wanted it to get out of my head :)
Thank you!
> Fix typo in subprocess input documentation

- internal/impl/opensearch/integration_test.go
- internal/impl/opensearch/output.go
fixes https://github.com/warpstreamlabs/bento/issues/162
> properly handle biri.Error

- website/docusaurus.config.js
- Change Algolia credentials to prevent old cached information showing up in search.
- I was unable to get this working on my local so I think we need to deply the docsite with this, then I will trigger a re-index.
> Change Algolia credentials to warpstream doc site

- internal/component/ratelimit/message_rate_limit.go
- internal/component/ratelimit/rate_limit_metrics.go
- internal/httpclient/client.go
- internal/impl/pure/processor_rate_limit.go
- internal/impl/pure/rate_limit_local.go
- internal/impl/pure/rate_limit_local_test.go
- public/service/environment.go
- public/service/rate_limit.go
- public/service/resources.go
- website/docs/components/rate_limits/local.md
- New `MessageAwareRateLimit` interface with an `Add()` method.
- `Add()` is passed a slice of internal messages or message-parts where the total bytes are summated
- `Access()` will increment the counter and block if the rate-limiting is reached
- Made some changes with airgapped* implementations since we need to allow `RateLimit` and `ratelimit.V1` to be backwards compatible since its in the public API
- The `local` rate limiter has these changes implemented whereas the `redis` one has not.
> Add new rate limiting functionality to rate-limit bytes

- internal/impl/kafka/input_kafka_franz.go
- website/docs/components/inputs/kafka_franz.md
- Add new rate limit field to Kafka input in order, which pauses polling when rate is exceeded.
> Add kafka rate limit

- go.mod
- go.sum
The original path to the `peercred` dependency is no longer resolvable. This PR adds a directive to circumvent this issue by pointing to the module path when installing.
See issue opened in upstream:
- https://github.com/AthenZ/athenz/issues/2842
> Fix unresolvable dependency path AthenZ/athenz in go.mod

- internal/impl/gcp/bigquery.go
- internal/impl/gcp/processor_bigquery_select.go
- internal/impl/gcp/processor_bigquery_select_test.go
- website/docs/components/processors/gcp_bigquery_select.md
Will enable things like: 
```yaml
pipeline:
processors:
- gcp_bigquery_select:
project: ${GGP_PROJECT}
table: ${! this.table } # test.people
columns_mapping: root = this.columns #["name", "age", "city"]
where:  ${! "city IN ("+this.args.join(",").re_replace_all("\\b\\w+\\b","?")+")" } # city IN (?,?,?)
args_mapping: root = this.args # ["London", "Paris", "Dublin"]
unsafe_dynamic_query: true
```
So that there is greater flexibility with this processor.
> add unsafe_dynamic_query to gcp_bigquery_select

- internal/impl/aws/processor_s3.go
- internal/impl/aws/processor_s3_integration_test.go
- website/docs/components/processors/aws_s3.md
This PR allows for objects to be deleted once consumed and processed by the S3 processor -- which has already been implemented by the S3 input component.
- Add a deferred delete operation that removes an S3 object after processing if it is read in without error.
- Adds a test case where this new field is enabled, with an existent check for the deleted object.
- Update docs.
> Add object deletion for AWS S3 processor

- internal/impl/gcp/input_cloud_storage.go
- internal/impl/gcp/input_cloud_storage_test.go
- website/docs/components/inputs/gcp_cloud_storage.md
This PR adds interpolation to the prefix property of gcp_cloud_storage. Although there are no messages in context at this stage (so we have only bloblang expressions), it seems to be more ergonomic to deal with dynamic file filtering as input.
> feat: added interpolation to the prefix property of gcp_cloud_storage.

- go.mod
- go.sum
upgrade github.com/docker/docker from v25.0.3 to v25.0.6
> fix CVE-2024-41110

- internal/impl/nats/integration_kv_test.go
- internal/impl/nats/processor_kv.go
The `nats_kv` processor removed all meta values from message on succes. That is not consistent behaviour with other operations.
- The operations `get` and `get_revision` now copy any pre existing meta values on success.
- Test `get` and `get_revision` as well as one other operation for consistency.
> fix for nats_kv to be consistent in passing meta values along

- internal/bundle/strict/bundle.go
- internal/bundle/strict/bundle_test.go
- internal/bundle/strict/package.go
- internal/bundle/strict/processor.go
- internal/bundle/strict/processor_strict_test.go
- website/docs/components/processors/about.md
Adds an atomic flag to all strict processors used to toggle whether strict mode is enabled or not. This is currently used to prevent strict mode being activated when a `try`, `catch`, or `switch` processor is present.
Future versions will better cater for these custom scenarios in strict mode, but for now, we'll favour declarative error handling over the experimental strict mode.
> Disable strict mode in the presence of incompatible processors

- internal/impl/mqtt/integration_test.go
Fixes & refactors the MQTT integration tests where a variable was being referenced that didn't exist.
See [this failed run](https://github.com/warpstreamlabs/bento/actions/runs/13381398243/job/37370452863#step:5:154) for reference.
> fix: MQTT integration test

- internal/impl/gcp/integration_bigquery_test.go
- internal/impl/gcp/integration_pubsub_test.go
Fixes the GCP integration tests where:
- Pub/Sub was trying to pull an image that no linger existed (see https://github.com/warpstreamlabs/bento/actions/runs/13381398243/job/37370452863#step:5:125).
- BigQuery run was flaky on linux so I'm changing the `--platform` in the hopes that this fixes things (see https://github.com/warpstreamlabs/bento/actions/runs/13381398243/job/37370452863#step:5:119).
> fix: GCP integration tests

- go.mod
- go.sum
Fixes vulnerability in golang.org/x/oauth2/jws
See the links below for more details.
https://security.snyk.io/vuln/SNYK-GOLANG-GOLANGORGXOAUTH2JWS-8749594
https://go.googlesource.com/oauth2/+/681b4d8edca1bcfea5bce685d77ea7b82ed3e7b3
> chore: upgrade golang.org/x/oauth2

- go.mod
- internal/batch/policy/policy.go
- internal/impl/lang/bloblang.go
`golang.org/x/exp/rand` has been deprecated and scheduled to be deleted.
Reference: https://github.com/golang/exp/commit/f9890c6ad9f380fd3cdb66a33843f522d4790e03
Reference: https://go.dev/doc/go1.22#math_rand_v2
> Replace `golang.org/x/exp/rand` with `math/rand/v2`

- internal/impl/gcp/integration_pubsub_test.go
can't run these in parallel because of the setting of env vars:
panic: testing: t.Setenv called after t.Parallel; cannot set environment variables in parallel tests [recovered]
panic: testing: t.Setenv called after t.Parallel; cannot set environment variables in parallel tests
> remove t.Parallel() in gcp_pubsub int. tests

- go.mod
- go.sum
- internal/impl/kafka/input_kafka_franz.go
- internal/impl/kafka/integration_sarama_test.go
- internal/impl/kafka/integration_test.go
- website/docs/components/inputs/kafka_franz.md
- Adds an `auto_offset_reset` field for specifying automatic offset consumption -- which takes presedence over the `start_from_oldest` field.
- Upgrades `franz-go` to `v1.18` to give us access to the `kgo.NewOffset().AtCommitted()` value when `auto_offset_reset` is `none`.
- Replaces the non-existent Docker image in the the Kafka integration tests.
> add: kafka_franz input support for auto offset reset field

- internal/impl/pure/scanner_csv.go
- internal/impl/pure/scanner_csv_test.go
- website/docs/components/scanners/csv.md
adds a couple of fields to the csv scanner
- expected_headers - optional list of strings to check the csv file headers against
- expected_number_of_fields - optional int that will check against the file's number of fields
> add expected_headers & expected_number_of_fields to csv scanner

- go.mod
- go.sum
Upgrade github.com/golang-jwt/jwt/v5 from v5.2.1 to v5.2.2.
Fixes vulnerability https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMGOLANGJWTJWTV5-9510922
> chore: upgrade golang-jwt

- internal/bundle/strict/bloblang.go
- internal/bundle/strict/bundle.go
- internal/bundle/strict/bundle_test.go
- internal/bundle/strict/package.go
- internal/cli/common/manager.go
- public/service/stream_builder.go
- Disables strict mode when using a Bloblang:
- `error` or `errored` function
- `catch` method
- The `switch` keyword/processor no longer disables strict mode.
- Fixes `TestStrictBundleOutput` DLQ test not cleaning up the temporary file.
- Added a `TestStrictBundleBloblangFunction` and `TestDisableStrictBundleBloblangMethods` test
> Disable strict mode with incompatible Bloblang functions & method

- internal/impl/aws/input_sqs.go
- internal/impl/aws/integration_sqs_test.go
Reformats the message attribute data from pascal case to snake case before assigning to metadata. i.e
- `SequenceNumber => sqs_sequence_number`
- `AWSTraceHeader => sqs_aws_trace_header`
> [SQS] Reformat SQS message attributes as metadata

- internal/impl/protobuf/processor_protobuf.go
- website/docs/components/processors/protobuf.md
The doc says `import_paths` should be a list of directories.
The code is actually using  https://pkg.go.dev/path/filepath#Walk  
Which gives us an option to pass a file path.
It is really helpful when a protocol buffer file is mounted from a configmap in Kubernetes, if we only specify the directory with bento, many copies of it will be mounted in dot directories (for changes purpose) and the walk will hit them and halt because it found duplicates.
By specifying the full path, we can solve that issue. (I tried using recent bento)
Not sure it was intended that way, but it should be kept, it is also how protoc `-I` works.
> Fixing protocol buffer import_paths documentation

- public/service/environment.go
- public/service/environment_test.go
When registering a new rate limit via the use of the plugin (`RegisterRateLimit`), the current assertion
https://github.com/warpstreamlabs/bento/blob/b2dd8d100dc4bfb234ffdbe3d78bc9cf8a5b3ef7/public/service/environment.go#L503
will always be false since it checks whether it corresponds to the **internal** MessageAwareRateLimit
https://github.com/warpstreamlabs/bento/blob/b2dd8d100dc4bfb234ffdbe3d78bc9cf8a5b3ef7/internal/component/ratelimit/message_rate_limit.go#L11-L26
Anybody using the plugin can only implement the **public** MessageAwareRateLimit
https://github.com/warpstreamlabs/bento/blob/b2dd8d100dc4bfb234ffdbe3d78bc9cf8a5b3ef7/public/service/rate_limit.go#L23-L37
Here, I add a new branch case to handle this registration via the plugin by also checking the public interface.
Note: …
> fix(rateLimit): fix plugin registration for custom byte-based limiters

- public/service/stream_builder.go
- public/service/stream_builder_test.go
The strict mode was added in https://github.com/warpstreamlabs/bento/pull/174
It works perfectly fine when running Bento from the CLI because the parsing of `error_handling.strategy` is handled there:
https://github.com/warpstreamlabs/bento/blob/9f291ba9eaede36faadfe964e0877254a375dfec/internal/cli/common/manager.go#L113-L119
However, the `error_handling.strategy` is not handled when running the Bento GO library (from streamBuilder.Build()).
Here, I am adding the same logic in the stream_builder so that it also reads a `error_handling.strategy: reject` from a config.
--------
EDIT: I am not sure about what we want in the `StrictBuild` case (since it is only used in a test for now, maybe it doesn't matter). 
I assume we want:
- if we are calling it from a `StrictBuild` => we want to make …
> fix(strictMode): handle strict mode in StreamBuilder when 'error_handling.strategy: reject'

- internal/impl/elasticsearch/integration_test.go
- internal/impl/elasticsearch/output.go
- fixes connectivity with elasticsearch using tls
- adds an integration test to check elasticsearch tls _without aws_
> fix tls connection with elasticsearch output when not using aws

- go.mod
- go.sum
- internal/impl/parquet/convert.go
- internal/impl/parquet/processor_decode.go
- internal/impl/parquet/processor_encode_test.go
- internal/impl/parquet/schema.go
- website/docs/components/processors/parquet_decode.md
- Bumps parquet-go from `0.23.0` to `0.24.0`
- Adds a new flag `use_parquet_list_format` that allows for LIST types to be decoded into the logical type format -- following breaking changes in the upstream.
- Adds `TestParquetDecodeListFormat` as well as `TestParquetDecodeListFormatEdgeCases` -- where the latter is skipped due to a lack of support for 2D (and higher dimensional) arrays being encoded by upstream.
Closes #359
> update(parquet-go): Bump parquet-go and handle new LIST logical type

- internal/impl/gcp/output_bigquery_storage.go
- internal/impl/gcp/output_bigquery_storage_test.go
- website/docs/components/outputs/gcp_bigquery_write_api.md
- Adds a new `message_format` field to `gcp_bigquery_write_api` that allows a user specify the format of incoming messages.
> feat(bigquery): Add direct protobuf support to BigQuery Write API sink

- internal/cli/blobl/resources/playground/assets/css/components.css
- internal/cli/blobl/resources/playground/assets/css/editor.css
- internal/cli/blobl/resources/playground/assets/css/theme.css
- internal/cli/blobl/resources/playground/index.html
- internal/cli/blobl/resources/playground/js/editor.js
- internal/cli/blobl/resources/playground/js/playground.js
- internal/cli/blobl/resources/playground/js/ui.js
- internal/cli/blobl/resources/playground/js/utils.js
- **Dark Mode**: Adds a dark mode theme
- **Improved Tooltips**: Updates the tooltip documentation with better links, markdown stripping, and redirects
- **Improved Formatter**:  Improves Bloblang's code formatter
References issue https://github.com/warpstreamlabs/bento/issues/370
> Add Dark mode to Bloblang editor

- Makefile
The WASM javascript file we're looking for is in `misc/wasm` in Go 1.23 and below... let's change this for now until the next go version update to 1.24.
See [WebAssembly: Getting Started](https://go.dev/wiki/WebAssembly#getting-started)
> For Go 1.23 and earlier, the wasm support files needed in this article are located in misc/wasm, and the path should be replaced when performing operations with files such as lib/wasm/wasm_exec.js.
> fix(action): Use correct path for WASM in docsite job

- config/template_examples/processor_log_and_drop.yaml
- internal/cli/common/reader.go
- internal/cli/common/service.go
- internal/cli/lint.go
- internal/cli/run.go
- internal/config/config_test.go
- internal/config/reader.go
- internal/config/reader_test.go
- internal/config/resource_reader.go
- internal/config/resource_reader_test.go
- internal/config/stream_reader.go
- internal/config/stream_reader_test.go
- internal/config/watcher_test.go
- internal/docs/field.go
- internal/docs/format_yaml.go
- internal/stream/manager/api.go
Currently if you run a config that contains a deprecated field or component - you will not get a warning. 
This PR adds warning logs when you create a stream with deprecated field/component when you create a stream via: 
- bento 'normal mode' `bento -c config.yaml` 
- bento 'streams mode' `bento streams ./*.yaml` 
- creation of streams via REST API 
It also will now print any deprecated warnings when calling `bento lint` without setting `--deprecated`. The new behaviour is: 
`bento lint config.yaml` -> print any deprecated warnings but still return exit code 0
`bento lint --deprecated config.yaml` -> print deprecated warnings but return exit code 1 (same as before the PR)
It will not change the behaviour when creating streams via the library using StreamBuilder. 
```
INFO Running main …
```
> Log warnings for deprecated fields

- internal/impl/aws/output_s3.go
Starting on v1.29 of the github.com/aws/aws-sdk-go-v2/config package, the default value for RequestChecksumCalculation is RequestChecksumCalculationWhenSupported. This breaks the behavior of the aws_s3 output during multipart uploads, since we're not adding a checksum to the request. We're setting it back to RequestChecksumCalculationWhenRequired.
See https://github.com/aws/aws-sdk-go-v2/discussions/2960#discussioncomment-12077210
> Fix multipart s3 uploads for aws_s3 output destination

- internal/impl/sql/azure/azure.go
- internal/impl/sql/conn_aws.go
- internal/impl/sql/conn_azure.go
- internal/impl/sql/conn_fields.go
- public/components/sql/base/package.go
- website/docs/components/caches/sql.md
- website/docs/components/inputs/sql_raw.md
- website/docs/components/inputs/sql_select.md
- website/docs/components/outputs/sql_insert.md
- website/docs/components/outputs/sql_raw.md
- website/docs/components/processors/sql_insert.md
- website/docs/components/processors/sql_raw.md
- website/docs/components/processors/sql_select.md
- website/docs/guides/cloud/azure.md
- website/sidebars.js
Adds `azure` fields to sql components (similar to the aws fields that enable iam auth) that enable auth to postgres running on azure with "entra auth".
> Azure cloud credentials sql

- public/service/shared_metrics.go
- public/service/shared_metrics_test.go
- public/service/stream_builder.go
This has been a source of frustration for us: when using StreamBuilder to create multiple streams, each stream creates its own metrics registry and HTTP server, which means exposing one port per stream if you want metrics from all of them. We wanted a way to have metrics from multiple StreamBuilder-built streams report into one prometheus registry.
This PR introduces a `SharedMetrics` abstraction that can be associated with any given `StreamBuilder`. Stream names can be used to automatically label metrics, similar to how Bento's streams mode works, making it easy to distinguish metrics from different streams in the shared registry.
```go
// Create shared metrics setup
sharedMetrics, err := service.NewSharedMetricsSetup(`
prometheus:
use_histogram_timing: false
`, 9090)
// Start shared …
```
> adds support for binding metrics from multiple StreamBuilders into one shared metrics instance

- internal/impl/kafka/input_kafka_franz.go
- internal/impl/kafka/input_kafka_franz_test.go
- internal/impl/kafka/output_kafka_franz.go
- internal/impl/kafka/output_kafka_franz_test.go
Handles the edge-case where no `seed_brokers` are set in the Bento config. 
In addition, since the franz-go library allows a new client to be initialised without any `seed_brokers`, the client ends up not connecting to any broker -- resulting in a no reads or writes taking place silently.
- Returns an error in the `input/kafka_franz` and `output/kafka_franz` components when no seed brokers are defined.
> fix(kafka_franz): Validate non-zero seed_brokers attribute

- internal/impl/sql/aws/aws.go
- internal/impl/sql/azure/azure.go
- internal/impl/sql/conn_aws.go
- internal/impl/sql/conn_azure.go
- internal/impl/sql/conn_fields.go
There is a race condition when initialising multiple sql components as the global `var AWSGetCredentialsGeneratorFn` can be called from multiple goroutines on connect.
- Rework the `sql/azure` and `sql/aws` subpackages to instead use `sync.Values` and no longer make unsafe-references a global variable.
> refactor(sql/conn): Rework SQL connection builder for AWS and Azure

- internal/impl/prometheus/metrics_prometheus.go
- internal/impl/prometheus/metrics_prometheus_test.go
- website/docs/components/metrics/prometheus.md
Adds a `use_default_registry` field to the Prometheus metrics config.
This solves a problem when using the StreamBuilder API, where the parent Go application exposes metrics on one port, but the Bento stream exposes its metrics on a different port. To simplify monitoring setup by only needing to scrape a single port, setting this field to true will cause Bento to use the default Prometheus registry rather than creating its own.
Resolves #486
> feat(metrics): use default Prometheus registry

- internal/impl/pure/bloblang_numbers_v2.go
- internal/impl/pure/bloblang_numbers_v2_test.go
- website/docs/guides/bloblang/functions.md
Adds a new cosine similarity function to bloblang pure methods. 
Allows a user to compare two non-empty and non-null numeric vectors.
> feat(bloblang/numbers_v2): Add cosine similarity bloblang function
